spring.application.name=cicd-github-actions-terraform-swarm
server.port=8080

# Expose Actuator health endpoint for Docker Swarm healthchecks
management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true
