spring.application.name=angular22-springboot4-signals
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/taskdb
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres
spring.sql.init.mode=always
