spring.application.name=enterprise-rag-spring-ai
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=1536
spring.datasource.url=jdbc:postgresql://localhost:5432/vectordb
spring.datasource.username=user
spring.datasource.password=password
