spring:
  application:
    name: finance-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/webcodein-realm

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
