spring:
  application:
    name: finance-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://placeholder.identity-provider.com/realms/webcodein

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
