server.port=8081

# Connect to the Keycloak server running on localhost:8080 via Docker Compose
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/webcodein-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/webcodein-realm/protocol/openid-connect/certs
